name: Go

on:
  create:
    tags:
      - *
env:
  dest: bin
  # update to match version
  ENGINE_REF: my-4.15.2


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
          fetch-depth: 1

    - name: create engine dir
      run: mkdir -p monibuca_xy/monibuca-engine

    - name: Checkout monibuca engine
      uses: actions/checkout@v4
      with:
        ref: ${{ env.ENGINE_REF }}
        fetch-depth: 1
        repository: yu-xiaoyao/monibuca-engine
        path: monibuca_xy/monibuca-engine

    - name: Set up Env
      run: echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Set beta
      if: contains(env.version, 'beta')
      run: echo "dest=beta" >> $GITHUB_ENV
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.8

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: runner.os−go−{ { hashFiles('**/go.sum') } }
        restore-keys: ${{ runner.os }}-go-        

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        version: v1.8.3
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: copy
      if: success() && startsWith(github.ref, 'refs/tags/')
      run:  |
        mkdir -p bin
        cp dist/m7s_${{ env.version }}_windows_amd64.tar.gz bin/m7s_windows_amd64.tar.gz
        cp dist/m7s_${{ env.version }}_darwin_amd64.tar.gz  bin/m7s_darwin_amd64.tar.gz 
        cp dist/m7s_${{ env.version }}_darwin_arm64.tar.gz  bin/m7s_darwin_arm64.tar.gz 
        cp dist/m7s_${{ env.version }}_linux_amd64.tar.gz   bin/m7s_linux_amd64.tar.gz 
        cp dist/m7s_${{ env.version }}_linux_arm64.tar.gz   bin/m7s_linux_arm64.tar.gz 
        ls bin

#    - name: docker build
#      if: success() && startsWith(github.ref, 'refs/tags/')
#      run:  |
#        tar -zxvf bin/m7s_linux_amd64.tar.gz
#        mv m7s monibuca_linux
#        docker login -u langhuihui -p ${{ secrets.DOCKER_PASSWORD }}
#        docker build -t langhuihui/monibuca:latest .
#        docker push langhuihui/monibuca:latest
#    - name: docker push
#      if: success() && !contains(env.version, 'beta')
#      run:  |
#        docker tag langhuihui/monibuca:latest langhuihui/monibuca:${{ env.version }}
#        docker push langhuihui/monibuca:${{ env.version }}